#version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${DB_LOGIN}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5434:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - mynetwork
    restart: unless-stopped

  db_test:
    image: postgres:16
    container_name: postgres-db-test
    environment:
      POSTGRES_USER: ${TEST_DB_USER}
      POSTGRES_PASSWORD: ${TEST_DB_PASSWORD}
      POSTGRES_DB: ${TEST_DB_NAME}
    ports:
      - "5435:5432"
    volumes:
      - pg_data_test:/var/lib/postgresql/data
    networks:
      - mynetwork
    restart: unless-stopped

volumes:
  pg_data:
  pg_data_test:

networks:
  mynetwork:
    external: true